# Generated by Django 5.2.1 on 2025-06-03 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la matière')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['nom'],
            },
        ),
        migrations.AddField(
            model_name='formateur',
            name='matieres',
            field=models.ManyToManyField(blank=True, to='core.matiere', verbose_name='Matières enseignées'),
        ),
        migrations.CreateModel(
            name='Coefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Valeur du coefficient')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveau', verbose_name='Niveau')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.option', verbose_name='Option')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matiere', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Coefficient',
                'verbose_name_plural': 'Coefficients',
                'unique_together': {('matiere', 'option', 'niveau')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Valeur de la note')),
                ('date_saisie', models.DateTimeField(auto_now_add=True, verbose_name='Date de saisie')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etudiant', verbose_name='Étudiant')),
                ('formateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.formateur', verbose_name='Formateur (optionnel)')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matiere', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'ordering': ['etudiant__nom', 'etudiant__prenom', 'matiere__nom'],
                'unique_together': {('etudiant', 'matiere')},
            },
        ),
    ]
