# Generated by Django 5.2.1 on 2025-06-03 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_matiere_formateur_matieres_coefficient_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emargement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_debut', models.DateTimeField(verbose_name='Date et heure de début')),
                ('date_heure_fin', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('salle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Salle de cours')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes additionnelles')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formateur', verbose_name='Formateur')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.matiere', verbose_name='Matière enseignée')),
            ],
            options={
                'verbose_name': 'Émargement',
                'verbose_name_plural': 'Émargements',
                'ordering': ['-date_heure_debut'],
            },
        ),
    ]
