# Generated by Django 5.2.1 on 2025-06-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_emargement'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='photo_de_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/', verbose_name='Photo de profil'),
        ),
    ]
