# Generated by Django 5.2.1 on 2025-06-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_etudiant_photo_de_profil'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='dernier_diplome',
            field=models.CharField(blank=True, choices=[('AUCUN', 'Aucun'), ('BEPC', 'BEPC'), ('BACCALAUREAT', 'Baccalauréat'), ('BTS', 'BTS / DUT'), ('LICENCE', 'Licence'), ('MASTER', 'Master'), ('DOCTORAT', 'Doctorat'), ('AUTRE', 'Autre')], max_length=50, null=True, verbose_name='Dernier diplôme obtenu'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='motivations',
            field=models.TextField(blank=True, null=True, verbose_name='Vos motivations pour nous rejoindre'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10, verbose_name='Sexe'),
        ),
    ]
