# Generated by Django 5.2.1 on 2025-06-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_etudiant_dernier_diplome_etudiant_motivations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/', verbose_name="Image de l'article"),
        ),
    ]
