# Generated by Django 5.2.1 on 2025-06-08 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_semestre_alter_note_options_note_semestre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmargementTemporaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_debut', models.DateTimeField(verbose_name='Date et heure de début')),
                ('date_heure_fin', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('salle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Salle de cours')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes additionnelles (du formateur)')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté')], default='EN_ATTENTE', max_length=20, verbose_name='Statut de validation')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('date_validation_rejet', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation/rejet')),
                ('motif_rejet', models.TextField(blank=True, null=True, verbose_name='Motif de rejet (si applicable)')),
                ('formateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formateur', verbose_name='Formateur')),
                ('matiere', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.matiere', verbose_name='Matière enseignée')),
                ('validateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emargements_valides_rejetes', to=settings.AUTH_USER_MODEL, verbose_name='Validateur/Rejeteur')),
            ],
            options={
                'verbose_name': 'Émargement Temporaire',
                'verbose_name_plural': 'Émargements Temporaires',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
