# Generated by Django 5.2.1 on 2025-06-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emargementtemporaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='prix_par_heure',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Prix par heure (FCFA)'),
        ),
    ]
