# Generated by Django 5.2.1 on 2025-06-29 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_formateur_prix_par_heure'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name="Nombre de j'aime"),
        ),
    ]
